export const homeObjOne = {
  lightBg: false,
  primary: true,
  imgStart: '',
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: `Contact Me`,
  description: `Im a Frontend Engineer, I have 1 year of expericence with Javascript`,
  headLine: `Javascript is my key Language`,
  lightText: true,
  topLine: 'Chaitanya',
  img: require('../../images/svg-1.svg').default,
  alt: 'display',
  start: '',
};

export const homeObjTwo = {
  lightBg: true,
  primary: false,
  imgStart: 'start',
  lightTopLine: false,
  lightTextDesc: false,
  buttonLabel: `Technologies I Use`,
  description: `React, Express, Mongo, Git, Github, Html, CSS, Node, Web Optimization`,
  headLine: `My Tech Stacl`,
  lightText: true,
  topLine: 'Chaitanya',
  img: require('../../images/Credit_card_payment.png').default,
  alt: 'Image',
  start: 'true',
};

export const homeObjThree = {
  lightBg: false,
  primary: true,
  imgStart: '',
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: `Contact Me`,
  description: `Im a Frontend Engineer, I have 1 year of expericence with Javascript`,
  headLine: `Javascript is my key Language`,
  lightText: true,
  topLine: 'Chaitanya',
  img: require('../../images/Mobile_re.png').default,
  alt: 'display',
  start: '',
};

export const homeObjFour = {
  lightBg: true,
  primary: false,
  imgStart: 'start',
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: `Github`,
  description: `Hire me for personal project or sign a contract`,
  headLine: `Javascript is my key Language`,
  lightText: true,
  topLine: 'Chaitanya',
  img: require('../../images/social_bio.png').default,
  alt: 'display',
  start: true,
};
